version: 0.2
phases:
 build:
  commands: 
  - mvn clean install
 post_build:
  commands:
  - mv target/SpyglassApplication-0.0.1-SNAPSHOT.jar SpyglassApplication-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - SpyglassApplication-0.0.1-SNAPSHOT.jar 
